name: Release Creation

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{github.event.release.tag_name}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/downtime-ethck.zip

    # create a zip file with all files required by the module to add to the release
    - run: zip -r ./downtime-ethck.zip module.json styles/ templates/ audit-log.js chooseRoll.js downtime.js gmConfig.js training.js README.md LICENSE EXAMPLES.md 

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./downtime-ethck.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}

    # Update the 'latest' release
    - name: Create Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      if: endsWith(github.ref, 'master')
      with:
        allowUpdates: true
        name: Latest
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./downtime-ethck.zip'
        tag: latest
        body: ${{ github.event.release.body }}
        
        
    - name: Update files
      id: commit_updated_files
      uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
      with:

        # The name of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_name: Ethck

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: ethck0720@gmail.com

        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Bump Module Version'

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
